In [9]:
import numpy as np
import matplotlib.pyplot as plt

def i(r):
    # intensity(r)
    return r

x = np.arange(-5, 5, 0.1)
y = np.arange(-5, 5, 0.1)
xx, yy = np.meshgrid(x, y) 
# meshgrid separates x and y coordinates into their own 2d arrays so that any function on a grid is vectorized 

z = i(np.sqrt(xx**2 + yy**2))
h = plt.contourf(x,y,z)

In [12]:
x = np.arange(-5, 6, 1)
y = np.arange(-5, 6, 1)
xx, yy = np.meshgrid(x,y)

print('xx\n', xx, '\n\n yy\n', yy)
print('\n ~sqrt(xx**2 + yy**2)')
float_formatter = lambda x: "%.0f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})
print(np.sqrt(xx**2 + yy**2))

xx
 [[-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]] 

 yy
 [[-5 -5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4 -4]
 [-3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4  4]
 [ 5  5  5  5  5  5  5  5  5  5  5]]

 ~sqrt(xx**2 + yy**2)
[[7 6 6 5 5 5 5 5 6 6 7]
 [6 6 5 4 4 4 4 4 5 6 6]
 [6 5 4 4 3 3 3 4 4 5 6]
 [5 4 4 3 2 2 2 3 4 4 5]
 [5 4 3 2 1 1 1 2 3 4 5]
 [5 4 3 2 1 0 1 2 3 4 5]
 [5 4 3 2 1 1 1 2 3 4 